### ISSUE TITLE
Not mapping keys on Magic Keyboard A1644

### ISSUE THREAD

**Issue by erttu** [samartzidis/RaspiKey#1]
Hey,

I absolutely love your WinAppleKey drivers but wanted to get rid of testsigning mode. 

I have performed the RaspiKey installation on my raspberry zero W for several times without success. I can connect to my A1644 keyboard, but it never maps any of the keys. Tried to perform the installation on a different pc, with different sd-cards, with different usb-cables, but none of it has worked. Any tips would be greatly appreciated. :) 

My setup:
Win10 Pro 64bit
Raspberry Zero W
32Gb micro sd card

**Comment by samartzidis** [comment]
One thing that I suspect happening is that RaspiKey for some reason detects your A1644 keyboard as a generic Bluetooth keyboard (probably because it shows up with a different device name). 

Try pairing your keyboard again and then load this url: **http://raspikey.local/log** 
If you see a line like the following then that's the case.
`LOG_INFO|(/home/pi/projects/raspikey/Main.cpp:153)|Using Generic report filter`

Rename it back to "Magic Keyboard" and try pairing it again.

**Comment by erttu** [comment]
Thank you for the rapid and elaborate answer!

This was indeed the problem, it is working flawlessly now. :) The original name of my keyboard was actually changed from the original and I tried changing the name today while troubleshooting, but I renamed it to "Apple Magic Keyboard" which obviously didn't work.

Thank you for your work in this small community, I appreciate it a lot.

**Comment by alpap** [comment]
Any chance I can rename the keyboard in windows 10?
