### ISSUE TITLE
Request for More Detailed Documentation on Key Remapping

### ISSUE THREAD

**Issue by gtusr** [samartzidis/RaspiKey#3]
I've looked through the code and cannot find a clear explanation anywhere for how to configure a custom keyboard remapping.  

I recently spent a significant amount of time figuring out how to remap modifier keys using the no-longer supported WinA1314 package.  This process was complicated by the fact that I already remap modifier keys on my laptop keyboard in the registry.   I wanted to preserve these remappings, which is why I was initially attracted to the WinA1314 package since it uses Lopes' Interception driver and the latter can distinguish between hardware devices when detecting and mutating input.

Unfortunately, the bluetooth connection between A1314 and Windows 10 is not all that reliable.  The problem is that upon waking up the laptop, sometimes the A1314 will not reconnect and a remove device + repairing is necessary to restore use of the device.  This is a hassle, since there are no command line tools available to automate this process when necessary.

So now I'm wondering if RaspiKey is a better solution.  First question of course is how reliable is the bluetooth reconnection between the Raspberry Pi Zero W and the A1314 after the host device has awoken from sleep?

And back to my original question, how can I customize the keyboard remapping in a manner similar to what WinA1314 provided through the registry?

Thanks in advance your help ... and for all of your hard work to produce this very useful software!

**Comment by samartzidis** [comment]
Hi @gtusr,

I would recommend to stop using WinA1314 as due to the "Lopes' Interception driver" is inherently open to vulnerabilities (basically anyone can potentially write a key logger for it in userland). I removed my code from GitHub long time ago, but it is impossible to delete every copy of it on the internet. I rewrote WinA1314 in the form of the minimalistic WinAppleKey driver, which is secure, but unfortunately requires Windows to run in Test Mode (as you probably already know).

In regards to your question about RaspiKey, the keymap json file is a an array of input key filters and output keys in the following format:

```json
[ 
  [input-modifier-mask, input-key-scancode, output-modifier-mask, output-key-scancode],
  ...
]
```

For instance a file such as this:
```json
[ 
  [null, "0x35", null, "0x64"],
  [null, "0x64", null, "0x35"]
]
```
will swap the following keys:
**KEY_GRAVE = 0x35 = (Keyboard ` and ~)** to **KEY_102ND = 0x64 = (Keyboard Non-US \ and |)**
The optional modifier-mask can be used to filter the Ctrl, Shift and Alt key combinations if needed. If not used, you set it to **null** (as in the above example).

You can refer to [this document](https://github.com/samartzidis/RaspiKey/blob/master/keymaps/usb_hid_keys.h) to find out the HID scan codes of specific keys.

In regards to the RaspberryPi Bluetooth connection stability, I am using RaspiKey for a couple of years already on a daily basis and never had any problems with it.

Regards.

**Comment by gtusr** [comment]
Thanks for your quick reply.  I kind of guessed the format for the keymap json files at the level of the example you provided, but was confused by the null entries, which are still not completely clear yet from your description of them.

1).   I'm assuming that if I wanted to map the key combination LShift-a to the number 7, I would use:

["0x02", "0x04", null, "0x24"]

2).  and that this would not map RShift-a to 7.

Now let's consider swapping a modifier key, which is obviously a very common use case.  

3).  For example, to generate LCtrl modifier by pressing LAlt modifier is this the correct format:

[null, "0xe2", null, "0xe0"] 

Note that I'm using KEY_LEFTCTRL here and not the mask KEY_MOD_LCTRL.  My assumption is that the mask entry is only used for remapping key combinations that use a modifier, but to remap the modifier itself, we need its actual scan codes and use the format in the example I provide above, where the modifier masks have both been set to null.

4).  Regarding the issue of security and Lopes' Interception driver, I'm wondering how much of an additional security threat does his software create that does not already exist on computers which are able to run (for example) Autohotkey scripts, which obviously includes a lot of machines out there on the internet.  AHK uses hooks of course to intercept (and examine) keyboard traffic, but as long as the source code of the script is available for inspection, the risk is seen as tolerable for many of us.   

If there is any additional technical information out there about what kind of additional threat Lopes' Interception driver creates for users, it would be helpful if you could link to it.  Passwords for bank sites unfortunately can be sniffed by a suitably crafted AHK script running without administrator privileges, and copying to clipboard as many password managers do, is not all that much more secure either.  Programs like KeePass have resorted to dual-channel approaches (combination of keystroke events and clipboard for different pieces of the password), but this level of obfuscation will usually not thwart a determined hacker. 

I'm considering using AutohotPy for some future AHK-style automation projects, but your concerns about the Interception driver are now raising concerns for me as well, and I'd like to better under the risks here.

**Comment by samartzidis** [comment]
Hi @gtusr, 

1) You would need to use:
```
[
  ["0x02", "0x04", "0x0", "0x24"]
]
```
You would intercept the "LAlt-A" key combination with the "0x02", "0x04" part as you've entered correctly. But then you would want to output only a "0x24" scancode without maintaining the modifier. What you entered would result to a "&" key instead of "7".

2) Correct. You would need an extra entry for this combination.

3) Under the current remapping scheme, you cannot fully remap (i.e. all possible combinations) a special key such as Shift, Ctrl or Alt with one mapping table entry. You can only remap individual combinations of modifier keys with other keys.

4) How big of a security risk it is depends on many factors really. This is a very big discussion. Technically it is a security risk and given the growing popularity of my (free) software that was dependent on it, I felt that this risk was growing as well. Once an attacker realises that there is a potentially exploitable user base vulnerable to a potential attack they may decide to exploit it. What the Lopes' driver technically does is that it creates a "userland" API that can be accessed by normal user programs to intercept keystrokes at the keyboard driver level (including ctrl-alt-del, which windows does not allow to intercept from user code!). Yes AHK and the user-level interception techniques it uses may potentially be used for "bad things", but it is technically less dangerous. Just to mention a few differences between AHK and the Lopes' driver. AHK runs under the context of a the current user logon session. You cannot run AHK under your own logon session and intercept keystrokes of others using the same keyboard later. Additionally AHK cannot intercept security sensitive keystrokes such as ctrl-alt-del. So in a few words, the Loper's driver exposes an additional and bigger attack surface (than AHK) that is a good thing if you can avoid putting into your system.

5) Correct. Again, the key remapping capabilities or Raspikey are quite basic. As far as I remember the Fn key gets translated (in A1644.cpp) before reaching into the remapping table (KeyMapReportFilter.cpp).

Thanks for your good words. I agree about the A1314, I also thought it was the best to date. I hope you can find Raspikey helpful even with its current remapping restrictions. I wish I had more spare time to invest into that project to keep everyone happy but I have a normal job and like most of us I believe, it's taking most of my spare time! :)

Regards.

**Comment by gtusr** [comment]
Thanks for clarifying these other issues.
